<?php
/*
+------------------------------------------------------------------------+
| Phady Framework                                                        |
+------------------------------------------------------------------------+
| Copyright (c) 2015                                                     |
+------------------------------------------------------------------------+
| Phady Framework is a complement of Phalcon Framework                   |
|                                                                        |
+------------------------------------------------------------------------+
| Authors: Alien fernandez Fuentes <alienfernandez85@gmail.com>          |
+------------------------------------------------------------------------+
*/

namespace Phady\Core;

/**
  * @class Phady\Core\NamespaceHandler -  Namespaces handlers for app
  *
  * @author  Alien Fernández Fuentes <alienfernandez85@gmail.com>
  * @package Core
  * @copyright (c) 2015
  * @version 1.0.0
  */
class NamespaceHandler
{

    /**
     * Namespace prefix of the app
     */
    const NS_APP_PREFIX = "App";

    /**
     * @var string scope - Scope of execution [mvc | cli]
     */
    private $scope;

    /**
     * @var string rootDir - Root app
     */
    private $rootDir;

    /**
     * @var array Array modules default namespace
     */
    private $nsModuleDefault;

    /**
     * @var array Array modules default namespace
     */
    public $nsModulePathDefault = [];

    /**
     * @var array Array of namespace generated by the app
     */
    private $namespaces = [];

    /**
     * @var array Array of modules of the app
     */
    private $modules = [];

    /**
     * @param string scope - Scope of execution [mvc | cli]
     * @param string rootDir - Root of the app
     * @param array modules Modules app
     */
    public function __construct($scope, $rootDir, $modules = []) {}

    /**
     * @function setModulesNamespace - Namespace modify the modules of the app
     */
    public function setModulesNamespace($modules) {}

    /**
     * @function getAllNamespaceApp - Get all the app ns
     */
    public function getAllNamespaceApp() {}
}
